build_vars:
  BP_PHP_SERVER: nginx
  BP_RUN_COMPOSER_INSTALL: "1"
  BP_PHP_ENABLE_CACHE_CONTROL: "false"
  BP_PHP_VERSION: "8.2" # optional
  BP_PHP_WEB_DIR: web # docroot

secrets:
  - HASH_SALT

volumes:
  public-files:
    mount_path: /workspace/web/sites/default/files
    size: 2

services:
  drupal-db:
    type: mysql
    attach_as: separate_variables
