type: 'php'
version: '8.2'

docroot: web

envs:  
  HASH_SALT: hello-world-1234
  CONFIG_VARS: '{"test":"hello world"}'

mounts:
  public-files:
    mountPath: /workspace/web/sites/default/files
    size: 2Gi
    backup: false

services:
  db1:
    type: 'mysql'
    version: '10'
    size: 2Gi
    backup: false
  
resources:
  cpu: "1"
  memory: "1Gi"
    
permissions:
  - path: web/sites/default/settings.php
    mode: a+w

